#!/bin/bash
#shell script
#gcc build and run loginwindow.c file
#author:zhaosenhua
#date:2016/6/22
#read -p  'please input build file name:' file
#echo $file
#gcc -c Loginfo.c -o Loginfo.o
#pkg=`pkg-config --cflags --libs gtk+-3.0`
gcc -std=c99 \
-o resol.o resol.c \
-o logincit.o logincit.c \
-o interface.o interface.c \
-o topwindow.o topwindow.c \
-o networkSet.o networkSet.c \
-o setting.o  setting.c \
-o loginwindow.o loginwindow.c \
-o curlc.o curlc.c \
-o Ovirtdispatch.o Ovirtdispatch.c \
-o vmlistwindow.o vmlistwindow.c \
-o Loginfo.o  Loginfo.c \
-o vms.o vms.c \
-o configxml.o configxml.c \
-o shencloud-ui main.c `pkg-config --cflags --libs gtk+-3.0` -lcurl -lmxml -L. -linterface
